In [4]:
import numpy as np

zeros_array = np.zeros((3,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
zeros_array = np.ones((3,5))
print(zeros_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
import numpy as np
array = np.arange(0,25)
print(array)
print(array.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [22]:
Newarray = array.reshape(5,5)
print(Newarray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [52]:
# print(Newarray[:,-4])
print(Newarray[0:5])
# indexing has single values(3,5)
# slicing has multipe values 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [56]:
anotherslice = Newarray[0:2] = 0
print(anotherslice)

0


In [57]:
print(Newarray)

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [60]:
# mask = np.NewArray([True, True , False , True , False])
# print(array[mask])

"shahid".startswith('s')

True